import com.tschuchort.compiletesting.SourceFile
import org.junit.jupiter.api.Test
import io.github.samhoby.kotlintojs.tests.BaseProcessorTest

/**
 * Prints the code generated by [io.github.samhoby.kotlintojs.processor.WrapperProcessor] for the complete README example.
 * Run with: `./gradlew :processor:test --tests "processor.GeneratedCodeDemoTest"`
 */
class GeneratedCodeDemoTest : BaseProcessorTest() {
    @Test
    fun `complete README example - all conversions`() {
        val source =
            SourceFile.kotlin(
                "CatalogService.kt",
                $$"""
                import io.github.samhoby.kotlintojs.annotations.JsExportClass
                import io.github.samhoby.kotlintojs.annotations.JsExportFunction
                import kotlinx.coroutines.Dispatchers
                import kotlinx.coroutines.withContext

                @JvmInline
                value class UserId(val value: String)

                @JsExportClass
                class CatalogService {
                    fun count(): Int = 0
                    fun tags(): List<String> = listOf("a", "b")
                    fun prices(): Map<String, Int> = mapOf("apple" to 3)
                    fun total(): Long = 42L
                    fun owner(id: UserId): String = id.value
                    suspend fun search(q: String): List<String> =
                        withContext(Dispatchers.Default) { listOf(q) }
                }

                @JsExportFunction
                fun greet(name: String): String = "Hello, $name"
                """.trimIndent(),
            )

        val files = compileWithOptions(listOf(source), mapOf("longAsBigInt" to "true"))

        files.sortedBy { it.name }.forEach { file ->
            println()
            println("----- ${file.name} -----")
            println(file.readText())
        }
    }
}
